import os
import pandas as pd
from pulp import *
import matplotlib.pyplot as plt
import numpy as np

# ---------------------------------------------------
# STAGE 2: DECISION OPTIMIZATION MODULE
# ---------------------------------------------------
# This function is designed to be called from Stage I
# Input: A DataFrame containing the Decision Grid
# Output: Results, Plots, and Optimization Matrices
# ---------------------------------------------------

def run_optimization_pipeline(input_df, output_dir=None):
    """
    Main function to run the MIP optimization and generate plots.
    
    Parameters:
    input_df (pd.DataFrame): The Decision Grid generated by Stage I.
                             Must contain columns: id, call, EBIT, MC, APR, etc.
    
    Returns:
    tuple: (final_solution_df, EBIT_matrix, APR_matrix)
    """
    
    # Create a working copy to avoid modifying the original DataFrame
    df = input_df.copy()

    if output_dir is not None:
        os.makedirs(output_dir, exist_ok=True)

    
    # ---------------------------------------------------
    # PREPROCESSING: zero-out EBIT for no-call strategies
    # ---------------------------------------------------
    df.loc[df["call"] == 0, "EBIT"] = 0
    
    # Basic vetting (Optional: You can comment these out in production)
    print("\n" + "="*50)
    print("STAGE II: OPTIMIZATION STARTED")
    print("="*50)
    print("Input Data Shape:", df.shape)
    print("\nSample Columns:", df.columns.tolist()[:10], "...")

    # ---------------------------------------------------
    # PARAMETERS & VARIABLES
    # ---------------------------------------------------
    # These can be made flexible later. For now, keeping them as per your spec.
    CPC = 0.75 
    B = 5500 
    eta = 1.5 

    # Binary choice variable for each feasible customer-offer row
    x = LpVariable.dicts("x", df.index, cat="Binary")

    # MIP problem
    prob = LpProblem("Bank_Offer_Optimization", LpMaximize)

    # ---------------------------------------------------
    # OBJECTIVE FUNCTION
    # ---------------------------------------------------
    # Objective: maximize total EBIT
    prob += lpSum(df.loc[i, "EBIT"] * x[i] for i in df.index)

    # ---------------------------------------------------
    # CONSTRAINTS
    # ---------------------------------------------------
    # 1. Each customer gets exactly one offer
    for cust_id, rows in df.groupby("id").groups.items():
        prob += lpSum(x[i] for i in rows) == 1

    # 2. Marketing budget constraint
    prob += lpSum(df.loc[i, "call"] * CPC * x[i] for i in df.index) <= B

    # 3. Return-on-marketing (ROM) constraint
    prob += (
        lpSum(df.loc[i, "EBIT"] * x[i] for i in df.index)
        >= eta * lpSum(df.loc[i, "MC"] * x[i] for i in df.index)
    )

    # ---------------------------------------------------
    # SOLVE
    # ---------------------------------------------------
    print("\nSolving Optimization Problem...")
    prob.solve()
    
    # Extract the chosen rows (The final offer list)
    solution = df[[x[i].value() == 1 for i in df.index]]

    # ---------------------------------------------------
    # PRINT RESULTS
    # ---------------------------------------------------
    print("\n" + "-"*30)
    print("OPTIMIZATION RESULTS")
    print("-"*30)
    print("Total EBIT:", value(prob.objective))
    print("Total Calls:", solution["call"].sum())
    print("Total Marketing Spend:", (solution["call"] * CPC).sum())
    if solution["MC"].sum() > 0:
        print("ROM:", solution["EBIT"].sum() / solution["MC"].sum())
    else:
        print("ROM: N/A (No Marketing Cost)")

    # ---------------------------------------------------
    # PLOT 1: APR Assignment Distribution
    # ---------------------------------------------------
    # Split into call vs no-call
    solution_call = solution[solution["call"] == 1]
    solution_nocall = solution[solution["call"] == 0]
    
    # Handle NA for no-call
    if not solution_call.empty:
        apr_counts = solution_call["APR"].value_counts().sort_index()
    else:
        apr_counts = pd.Series(dtype=int)
        
    # Add NA count for no-call customers
    apr_counts.loc["NA"] = len(solution_nocall)
    
    # Reindex to ensure NA is first
    if not apr_counts.empty:
        apr_counts = apr_counts.reindex(["NA"] + [str(i) for i in apr_counts.index if i != "NA"])
    
    # Plot
    plt.figure(figsize=(10, 6))
    plt.bar(apr_counts.index.astype(str), apr_counts.values)
    
    for i, v in enumerate(apr_counts.values):
        plt.text(i, v, str(v), ha="center", va="bottom")
    
    plt.xlabel("APR Level (including NA for no call)")
    plt.ylabel("Number of Customers")
    plt.title("APR Assignment Distribution (Original Parameters)")
    plt.tight_layout()
    if output_dir is not None:
        plt.savefig(os.path.join(output_dir, "apr_assignment_distribution.png"), dpi=300, bbox_inches="tight")
    plt.show()

    # ---------------------------------------------------
    # GRID SEARCH: Sensitivity Analysis
    # ---------------------------------------------------
    print("\nRunning Sensitivity Analysis (Grid Search)...")
    
    # Parameters
    B_grid = [250, 500, 750, 1000, 1250, 1500, 2000, 4000, 6000, 8000, 10000]
    eta_grid = [1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0]
    
    APR_call_mat = np.zeros((len(eta_grid), len(B_grid)))
    EBIT_mat = np.zeros((len(eta_grid), len(B_grid)))

    # Solver settings to speed up (as per your original code)
    solver = PULP_CBC_CMD(msg=False, gapRel=0.0005, timeLimit=60)

    # Nested loops
    for i, eta in enumerate(eta_grid):
        for j, B in enumerate(B_grid):
            # --- Re-define the problem inside the loop ---
            x_temp = LpVariable.dicts("x", df.index, cat="Binary")
            prob_temp = LpProblem("Bank_Offer_Optimization", LpMaximize)
            
            # Objective
            prob_temp += lpSum(df.loc[k, "EBIT"] * x_temp[k] for k in df.index)
            
            # Constraints
            # 1. One offer per customer
            for cust_id, rows in df.groupby("id").groups.items():
                prob_temp += lpSum(x_temp[k] for k in rows) == 1
                
            # 2. Budget
            prob_temp += lpSum(df.loc[k, "call"] * CPC * x_temp[k] for k in df.index) <= B
            
            # 3. ROM
            prob_temp += (lpSum(df.loc[k, "EBIT"] * x_temp[k] for k in df.index) 
                         >= eta * lpSum(df.loc[k, "MC"] * x_temp[k] for k in df.index))
            
            # Solve
            prob_temp.solve(solver)
            
            # Store EBIT
            EBIT_mat[i, j] = value(prob_temp.objective)
            
            # Calculate Avg APR for calls
            total_call = 0
            total_apr_call = 0
            for k in df.index:
                if x_temp[k].value() > 0.5: # If selected
                    if df.loc[k, "call"] == 1: # If it's a call
                        total_call += 1
                        total_apr_call += df.loc[k, "APR"]
            
            if total_call > 0:
                APR_call_mat[i, j] = total_apr_call / total_call
            else:
                APR_call_mat[i, j] = np.nan

    # ---------------------------------------------------
    # PLOT 2: EBIT Heatmap
    # ---------------------------------------------------
    plt.figure(figsize=(12, 8))
    EBIT_plot = EBIT_mat.copy()
    EBIT_plot[EBIT_plot < 0] = np.nan
    
    plt.imshow(EBIT_plot, aspect="auto", cmap="viridis")
    
    plt.xticks(range(len(B_grid)), B_grid, fontsize=9, rotation=45)
    plt.yticks(range(len(eta_grid)), eta_grid, fontsize=9)
    
    plt.xlabel("Budget Constraint (B)")
    plt.ylabel("ROM threshold (η)")
    plt.title("Total EBIT Across Constraint Grid")
    
    # Add text labels
    for i in range(len(eta_grid)):
        for j in range(len(B_grid)):
            val = EBIT_mat[i, j]
            if val < 0 or np.isnan(val):
                label = "NA"
            else:
                label = f"{val:.0f}"
            plt.text(j, i, label, ha="center", va="center", color="white", fontsize=8)
    
    plt.colorbar(label="EBIT")
    plt.tight_layout()
    if output_dir is not None:
        plt.savefig(os.path.join(output_dir, "grid_total_ebit_heatmap.png"), dpi=300, bbox_inches="tight")
    plt.show()

    # ---------------------------------------------------
    # PLOT 3: Average APR Heatmap
    # ---------------------------------------------------
    plt.figure(figsize=(12, 8))
    APR_plot = APR_call_mat.copy()
    # Mask APR wherever EBIT is negative/invalid
    APR_plot[EBIT_mat < 0] = np.nan
    
    plt.imshow(APR_plot, aspect="auto", cmap="plasma")
    
    plt.xticks(range(len(B_grid)), B_grid, fontsize=9, rotation=45)
    plt.yticks(range(len(eta_grid)), eta_grid, fontsize=9)
    
    plt.xlabel("Budget Constraint (B)")
    plt.ylabel("ROM threshold (η)")
    plt.title("Average APR Across Constraint Grid")
    
    # Add text labels
    for i in range(len(eta_grid)):
        for j in range(len(B_grid)):
            val = APR_plot[i, j]
            if np.isnan(val):
                label = "NA"
            else:
                label = f"{val:.2f}"
            plt.text(j, i, label, ha="center", va="center", color="white", fontsize=8)
    
    plt.colorbar(label="Avg APR for Call=1")
    plt.tight_layout()
    if output_dir is not None:
        plt.savefig(os.path.join(output_dir, "grid_average_apr_heatmap.png"), dpi=300, bbox_inches="tight")
    plt.show()

    # ---------------------------------------------------
    # RETURN RESULTS
    # ---------------------------------------------------
    # This sends data back to Stage I for saving
    return solution, EBIT_mat, APR_call_mat

# ---------------------------------------------------
# END OF FILE
# ---------------------------------------------------
